# Generated by Django 4.2.2 on 2023-06-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_product_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_uuid',
        ),
    ]
