import { StationDetailsContainer } from "@/components/styled/Layouts";
import { InfoMapCard } from "./components/InfoMapCard";
import { StationDetails } from "@/interface/stationInfo";
import getStation from "@/utils/getStation";

type Props = {
  params: {
    place_id: string;
  };
};

async function PageMap({ params: { place_id } }: Props) {
  const stationData: Promise<StationDetails> = getStation(place_id);
  const station = await stationData;
}

export const metadata = {
  title: "GasGo",
  description: "Generated by create next app",
  icons: {
    icon: "/GasGo-web-solo.svg",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <StationDetailsContainer>
        {children}
        <InfoMapCard/>
      </StationDetailsContainer>
    </>
  );
}
