# Generated by Django 4.0.10 on 2023-05-16 07:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('html_attributions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('photo_reference', models.CharField(max_length=500)),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viewport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('northeast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='northeast', to='stations_app.location')),
                ('southwest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='southwest', to='stations_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_status', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('icon_background_color', models.CharField(max_length=10)),
                ('icon_mask_base_uri', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('reference', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=50)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('user_ratings_total', models.IntegerField()),
                ('vicinity', models.CharField(max_length=100)),
                ('geometry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations_app.geometry')),
                ('photos', models.ManyToManyField(to='stations_app.photo')),
            ],
        ),
        migrations.AddField(
            model_name='geometry',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations_app.location'),
        ),
        migrations.AddField(
            model_name='geometry',
            name='viewport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stations_app.viewport'),
        ),
    ]
